# Command to build this image -> docker build --no-cache -t herupa .
# Command to run the container -> docker run -id herupa

FROM python:3.9.13-alpine3.16

ENV DISCORD_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
ENV GITHUB_PAT=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
ENV WEBHOOK_URL=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# Updating the 
RUN apk update

# Installing the packages we need
RUN apk add wget unzip vim

# Installing all the files from the github as a zip
RUN wget https://github.com/MBarc/Herupa-Discord-Bot/archive/refs/heads/main.zip -O discord_bot.zip

# Unzipping the files and cleaning up
RUN unzip discord_bot.zip && rm discord_bot.zip

# Renaming the folder
RUN mv Herupa-Discord-Bot-main /herupa

# Installing of Herupa's dependencies
RUN apk add --no-cache --virtual .pynacl_deps build-base python3-dev libffi-dev gcc ffmpeg opus
RUN pip install Cmake wheel cffi
RUN pip install -r /herupa/Herupa/requirements.txt
RUN touch /herupa/OverhaulDetectorLog.txt
RUN chmod 777 /herupa/queue.json

RUN echo "* * * * * cd /herupa && python /herupa/OverhaulDetector.py >> /herupa/OverhaulDetectorLog.txt" | crontab -
RUN echo "# LEAVE THIS EMPTY LINE" >> /etc/crontabs/root

ADD start.sh /herupa/Herupa/
RUN chmod +x /herupa/Herupa/start.sh

ENTRYPOINT [ "/herupa/Herupa/start.sh"]
