version: '3.1'

services:

  herupa:
    build:
      context: .
      dockerfile: HerupaDockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GITHUB_PAT: ${GITHUB_PAT}
      WEBHOOK_URL: ${WEBHOOK_URL}
    container_name: herupa
    restart: unless-stopped

  herupa_mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
