services:

  herupa:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GITHUB_PAT: ${GITHUB_PAT}
      WEBHOOK_URL: ${WEBHOOK_URL}
    container_name: herupa
    entrypoint: /herupa/Herupa/start.sh
    stdin_open: true
    tty: true
    restart: always
    security_opt:
      - seccomp=unconfined
    depends_on:
      - herupa_mongo

  herupa_mongo:
    image: mongo:4.4.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # change this if you want
      MONGO_INITDB_ROOT_PASSWORD: admin # change this if you want
    ports:
      - 27017:27017
